CREATE DATABASE IF NOT EXISTS portafoliodelta_db;
USE portafoliodelta_db;

CREATE TABLE IF NOT EXISTS notas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombreyapellido VARCHAR(255) NOT NULL,
  usuario VARCHAR(255) DEFAULT NULL,
  email VARCHAR(255) NOT NULL,
  nota VARCHAR(1000) NOT NULL,
  fechanota VARCHAR(255) NOT NULL
);